version: "3"

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: ${NETWORK}

services:
  mailserver:
    restart: unless-stopped
    build:
      context: ./postfix
    container_name: livecom-mailserver
    domainname: ${DOMAINNAME}
    hostname: ${HOSTNAME}
    ports:
      - "2525:25"
      - "${ROUNDCUBE_PORT}:80"
      - "1110:110"
      - "1143:143"
      - "4465:465"
      - "9393:993"
      - "9595:995"
    env_file:
      - .env
    volumes:
      - ./data/vmail:/var/vmail
      - ./data/mysql:/var/lib/mysql
      - ./data/log:/var/log
      - ./assets/dkim:/etc/opendkim/domainkeys
      - ./assets/certs:/etc/postfix/certs
    networks:
      net:
